### ISSUE TITLE
SOF Loadouts

### ISSUE THREAD

**Issue by jerkinmerkin** [Spearhead-Gaming-Milsim/OP_Red_November#7]
Here is the [config.cpp](http://pastebin.com/JAB0fStu) for SOF.  You will be playing as the Red Star Brigade, a special branch of the the Worker's Volunteer Guard.  The Red Star Brigade, also known as Yakavetta's Vipers, is paramilitary group run by the crime boss turned freedom fighter Alexander Yakavetta.  Supplies are limited, but the RSB has access to more ammunition and supplies than the rest of the WVG thanks to Yakavetta's underground ties.  There aren't many special weapons given to you guys, you'll just have to "acquire" them like everyone else.  Here's some screenshots:

(http://i.imgur.com/YHX27Vr.jpg?2)

(http://i.imgur.com/UN9d7AU.jpg)

(http://i.imgur.com/IG5koG0.jpg)

(http://i.imgur.com/yzXr551.jpg)

**Comment by jerkinmerkin** [comment]
**SOF** (Slot names are still WIP, but you get the idea of what I'm going for)

CO
PLT

TL
RTO
Sniper
IED Specialist
Medic
Weapons Specialist

TL
RTO
DM
IED Specialist
Medic
Weapons Specialist

TL
Gillie Sniper
Gillie Spotter

**Vehicles**

3x Pickup PKs
1x Pickup

**Comment by SHG-LIM** [comment]
Our slots are already clearly named and laid out for you.

Reference the ODA and ISR channel descriptions on TeamSpeak. If you still have questions feel free to ask Yak.

**Comment by jerkinmerkin** [comment]
I know this lim, but you guys aren't playing as super elite delta force rangers.  The slots are adjusted to fit the scenario.

**Comment by SHG-LIM** [comment]
Right. Message received.

**Comment by Yakavetta** [comment]
This is going to stop. I'm willing to work with you to make our Unit fit the scenario, but you will not dictate how we play. Our slots, our SOP's and our doctrine are laid out. We will conform to the time period in terms of equipment, but not in terms of our structure, or how we play. Here's some light reading for you to get caught up. 

https://spearheadgaming.net/index.php?/topic/3457-spearhead-20-and-new-mil-sim-structure/#
https://spearheadgaming.net/index.php?/topic/3512-unit-sop-thread/

Since you've already told me once you won't read this, here's some highlights:

"The new structure, will allow groups/platoons to develop their own culture and esprit de corp, a throw back to our old official group days, while falling under a one unit structure."

"There will be groups with different and/or better gear.  Don’t fucking whine about it."

"Special Forces Company will be responsible for reconnaissance, intelligence gathering and analysis utilizing ISR

Special Forces Company will be the premier assault and direct action force for Spearihead."

We do not have IED specialists, demolitions, explosives...whatever else there is. Our layout is clearly defined there.  Our mission isn't to scrounge up gear, this isn't an RP server. It's defined above. Further, our equipment requirements are already defined as well. We will work with you to make them appropriate to this time period, but our mission set is quite clear.  

Welcome back, welcome to Soearhead 2.0.

**Comment by coachwn** [comment]
Please reference my issue tagged in [here](https://github.com/Spearhead-Gaming-Milsim/SF-loadouts/issues/1).

**Comment by jerkinmerkin** [comment]
okay yak, I'm going to explain my reasonings for you since you're head is too far up your ass to understand.

Your layout is fucking retarded.  You will not always play as a super elite super solider.  When I want you to play as an ODA I will.  Not on this mission.  Get the fuck over it.  Nobody gives a fuck and is enjoying the missions except SOF, which doesn't really matter since only two of you play anyways.

Breechers = IED specialists.  My reasoning, Taviana is a map with very few enterable building.  Your script is of no use on it, therefore breechers are not of much use.  This is why I made them IED specialists.  If you have a better suggestion I'm all ears.

ISR Team.  Youre a paramilitary group.  They have no idea what the fuck an ISR team is.  They don't have UAVs.  You only have three members in the team.  Get more members, you get more slots.  Same goes for having three teams.  You have what?  Seven members?  Two active?  I'm not going to waste time making slots that will never be played.  And no, im not singling out SOF, I've limited infantry slots  since they cannot fulfill them as well.

Hey look, I can link things too!

https://spearheadgaming.net/index.php?/topic/3726-just-a-quick-reminder-to-everyone/

You don't get Gucci gear.  Now wipe tears and blow me.

**Comment by Yakavetta** [comment]
You need to take this up with Nichols.  Clearly you aren't going to listen to me so as you suggested, I spoke with Dodds. He spoke with Nichols. You need to before you come unglued dude.

I'm trying to work with you on this to help match our SOP with your feel, but this isn't working. Talk with Nichols.

**Comment by therealdodds** [comment]
Alright. Have some fucking professionalism. I will not tolerate this name-calling, petty shit.  Jerkin. If you're not clear on what and what isn't at the mission makers discretion, talk to me.

We will take this offline, as neither of you fucks are going to comment again on this post except with "Roger, understood."

The following applies to all missions:

- Mission maker, in coordination with unit COs, assigns equipment in line with the scenario. Equipment will be in line with the scenario. Final say on discrepancies or issues is approved by Nichols or myself, but we'll generally side with the mission maker.

- Unit slots are standard. They will not and should not change. These are the internally and externally (TF HQ and JCS approved MTOE). It really won't matter what the hell theyre named so long as the slots are broken down per individual unit SOP.

If there's questions, talk to me. If I see this shit again, I will ban the ever lasting fuck out of people. This cancerous shit will not spread.

**Comment by jerkinmerkin** [comment]
You need all the slots, fine can be done.  What you see above is just on paper.  I've given you two items that can actually use your input, what to do with the UAV specialist and breecher.  If you've even looked at the config, I've taken care to take your equiptment requirements and unit roles and adjust them to what's available in the scenario.  You'll be more than capable to accomplish your mission based on what's available to you.  If there's something you disagree with, post specifics, but don't tell me I haven't read your unit SOP because I have.  I'm not trying you give you guys "bad gear" I'm just trying to fit the scenario.  Your unit is not singled out, you just drive me nuts with all the complaints I get about gear.

**Comment by jerkinmerkin** [comment]
See Nichol's thread.
